### ISSUE TITLE
Does not work after fresh install

### ISSUE THREAD

**Issue by hutou** [arecarn/crunch.vim#47]
Just installed the 2 plugins (selection and crunch) on Vim version 7.4.854 with vundle, but cannot get them to work at all (Vim version is compiled with float option)
Here is a simple test I did after installation:
> Open gvim
i
1 +  2
\<ESC>
0g=$

displays : 
>Erreur détectée en traitant function crunch#operator :
ligne    2 :
E117: Fonction inconnue : util#debug#print_header

and typing 
>:Crunch 1+2

in command mode displays :
>Erreur détectée en traitant function crunch#command..<SNR>75_handle_cmd_input :
ligne    4 :
E117: Fonction inconnue : util#debug#print_header
ligne    5 :
E117: Fonction inconnue : util#debug#print_var_msg
ligne   12 :
E117: Fonction inconnue : util#debug#print_var_msg
ligne   16 :
E117: Fonction inconnue : util#debug#print_var_msg
Erreur détectée en traitant function crunch#command..crunch#cmd_line_crunch..<SNR>75_valid_line :
ligne    5 :
E117: Fonction inconnue : util#debug#print_header
Erreur détectée en traitant function crunch#command :
ligne    7 :
E171: :endif manquant
Appuyez sur ENTRÉE ou tapez une commande pour continuer

Thanks for help

**Comment by arecarn** [comment]
Thanks for reporting this I'll take a look at it later today.

**Comment by arecarn** [comment]
Did you end up getting it working?

**Comment by hutou** [comment]
Sorry, all is Ok after a :PluginUpdate

**Comment by arecarn** [comment]
No problem glad it worked for you  :)

**Comment by MintPaw** [comment]
I had this issue today as well, the problem is that if you just "git clone" the repo you don't by default get the autoload/util submodule, few people understand submodules.

I think this is a bit of a problem, if you're using something like Vundle with a plugin manager then it'll deal with it because of PluginUpdate, but if you're using something like pathogen or just git clone the then you have to know to "git clone --recursive" and it makes storing dotfiles in a git repo pretty painful.

**Comment by arecarn** [comment]
I agree with you, I've realized it was probably a mistake to use a submodule. When I get around to it I'll remove it.

**Comment by arecarn** [comment]
I've removed the submodule, so this shouldn't happen anymore
